#!/usr/bin/env bash
# Generate ~/.ssh/config entries for seamless laptop -> k8s access via the bastion.
#
# Reads `tofu output -json` from the prod directory and writes:
#   ~/.ssh/config.d/proxmox-k8s.conf
# with:
#   - Host bastion            (entry from admin network, ForwardAgent yes, connection multiplexing)
#   - Host <each k8s node>    (ProxyJump bastion, ForwardAgent yes)
#
# With this in place, `ssh control-plane-00` on the laptop auto-forwards through bastion.
# The private key is never stored on the bastion (agent forwarding).
#
# Usage:  ./gen-ssh-config.sh [prod-dir]
#   prod-dir defaults to ../../iac/prod relative to this script.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROD_DIR="${1:-$SCRIPT_DIR/../../iac/prod}"
PROD_DIR="$(cd "$PROD_DIR" 2>/dev/null && pwd)" || { echo "ERROR: prod dir not found: $1" >&2; exit 1; }

command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required (brew install jq)." >&2; exit 1; }
if command -v tofu >/dev/null 2>&1; then TF=tofu
elif command -v terraform >/dev/null 2>&1; then TF=terraform
else echo "ERROR: tofu or terraform is required." >&2; exit 1; fi

echo "Reading outputs from $PROD_DIR ..."
OUT="$("$TF" -chdir="$PROD_DIR" output -json)"

BASTION_IP=$(echo "$OUT"   | jq -r '.bastion_access.value.ip')
BASTION_PORT=$(echo "$OUT" | jq -r '.bastion_access.value.port')
BASTION_USER=$(echo "$OUT" | jq -r '.bastion_access.value.user')
[[ -n "$BASTION_IP" && "$BASTION_IP" != "null" ]] || { echo "ERROR: bastion_access.ip is empty. Run 'tofu -chdir $PROD_DIR output' to check." >&2; exit 1; }

# All node targets (name<TAB>ip), control-planes first, then workers, then kubespray.
NODES=$(echo "$OUT" | jq -rf <(cat <<'JQ'
[ .control_plane_nodes.value[], .worker_nodes.value[], .kubespray_node.value[] ]
| .[] | select(.ip != null and .ip != "") | [ .name, .ip ] | @tsv
JQ
))

SSH_DIR="$HOME/.ssh"
CONF_DIR="$SSH_DIR/config.d"
CONF="$CONF_DIR/proxmox-k8s.conf"
mkdir -p "$CONF_DIR"
chmod 700 "$SSH_DIR"

TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
{
  echo "# Generated by scripts/admin/gen-ssh-config.sh on $TS — do not edit; re-run to update."
  echo "# Bastion: entry point from the admin network."
  echo "Host bastion"
  echo "    HostName ${BASTION_IP}"
  echo "    Port ${BASTION_PORT}"
  echo "    User ${BASTION_USER}"
  echo "    ForwardAgent yes"
  echo "    ServerAliveInterval 30"
  echo "    StrictHostKeyChecking accept-new"
  echo "    ControlMaster auto"
  echo "    ControlPath %d/.ssh/%C"
  echo "    ControlPersist 10m"
  echo
  echo "# k8s nodes — reached by ProxyJump through bastion (agent forwarded, no key on bastion)."
  while IFS=$'\t' read -r name ip; do
    [[ -z "$name" ]] && continue
    echo "Host ${name}"
    echo "    HostName ${ip}"
    echo "    ProxyJump bastion"
    echo "    User ubuntu"
    echo "    ForwardAgent yes"
    echo "    StrictHostKeyChecking accept-new"
    echo
  done <<< "$NODES"
} > "$CONF"
chmod 600 "$CONF"

# Ensure ~/.ssh/config includes the config.d drop-in.
# IMPORTANT: the Include MUST sit at the top of the file, BEFORE any Host block.
# OpenSSH scopes an Include inside the nearest open Host/Match block — placing it
# after a Host block (even with blank lines / comments in between, which do NOT
# close the block) silently scopes the included Hosts away and aliases won't resolve.
touch "$SSH_DIR/config"
BACKUP="$SSH_DIR/config.bak"
cp "$SSH_DIR/config" "$BACKUP"
if grep -Eq '^[[:space:]]*Include[[:space:]].*config\.d/\*\.conf' "$SSH_DIR/config"; then
  # Remove any existing drop-in Include line(s) so we can re-place it at the top.
  grep -vE '^[[:space:]]*Include[[:space:]].*config\.d/\*\.conf' "$SSH_DIR/config" > "$SSH_DIR/config.tmp" || true
else
  cp "$SSH_DIR/config" "$SSH_DIR/config.tmp"
fi
{
  printf '# Load drop-in configs (keep at TOP — must precede any Host block)\n'
  printf 'Include ~/.ssh/config.d/*.conf\n\n'
  cat "$SSH_DIR/config.tmp"
} > "$SSH_DIR/config"
rm -f "$SSH_DIR/config.tmp"
chmod 600 "$SSH_DIR/config"
echo "Ensured 'Include ~/.ssh/config.d/*.conf' at top of ~/.ssh/config (backup: $BACKUP)"

NODE_COUNT=$(echo "$NODES" | grep -c . || true)
cat <<EOF

Wrote: ${CONF}
  bastion : ${BASTION_USER}@${BASTION_IP}:${BASTION_PORT}
  nodes   : ${NODE_COUNT} target(s) via ProxyJump

Next steps (on this laptop):
  1. Load the private key matching ./ssh/id_ed25519.pub into the agent:
       ssh-add ~/.ssh/<your-private-key>
  2. Connect to any node — it auto-forwards through bastion:
       ssh control-plane-00
       ansible all -m ping -i <your-inventory>
EOF
